var ctable_lang = {
    en: {
        current_page: 'Page',
        no_pages: 'No pages',
        from: 'from',
        show_by: 'Show by',
        to_last_page: 'To last page',
        to_next_page: 'To next page',
        to_prev_page: 'To previous page',
        to_first_page: 'To first page',
        delete_row_ask: 'Delete this row?',
        save: 'Save',
        discard: 'Discard',
        edit_rec: 'Edit this row',
        delete_rec: 'Delete this row',
        add_rec: 'Add row',
        actions: 'Other actions',
        open_subtable: 'Open subtable',
        no_data: 'No rows',
        error: 'Error: ',
        server_error: 'Server side error: ',
        no_filter: 'No filter',
        no_file: 'No file',
        file_present: 'File present',
        multiple_files: 'Files: ',
        file_to_large: 'File too large',
        file_wrong_extention: 'File have a wrong type',
        file_filter_no: 'No file',
        file_filter_yes: 'Have a file',
        reload: 'Reload',
        loading: 'Loading...',
        all: 'All',
        file_only_one: 'Only one file should be uploaded'
    },
    ru: {
        current_page: 'Страница',
        no_pages: 'Нет страниц',
        from: 'из',
        show_by: 'Показывать по',
        to_last_page: 'На последнюю страницу',
        to_next_page: 'На следующую страницу',
        to_prev_page: 'На предыдущую страницу',
        to_first_page: 'На первую страницу',
        delete_row_ask: 'Удалить запись?',
        save: 'Сохранить',
        discard: 'Отменить',
        edit_rec: 'Изменить запись',
        delete_rec: 'Удалить запись',
        add_rec: 'Добавить запись',
        actions: 'Другие действия',
        open_subtable: 'Открыть подтаблицу',
        no_data: 'Нет данных',
        error: 'Ошибка: ',
        server_error: 'Ошибка сервера: ',
        no_filter: 'Нет фильтра',
        no_file: 'Нет файла',
        file_present: 'Файл загружен',
        multiple_files: 'Файлы: ',
        file_to_large: 'Файл слишком велик',
        file_wrong_extention: 'Файл имеет недопустимый тип',
        file_filter_no: 'Нет файла',
        file_filter_yes: 'Файл загружен',
        reload: 'Перезагрузить',
        loading: 'Загрузка...',
        all: 'Все',
        file_only_one: 'Может быть загружен только один файл'
    }
}


